name: Generate Colorful Snake Animation

on:
  schedule: # Runs every day at 12 AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Colorful Snake
        uses: Platane/snk@v3
        with:
          github_user_name: TeddyO323
          outputs: dist/github-contribution-grid-snake.svg
          # Color options
          color_snake: ff0000 # Red snake
          color_dots: 00ff00,ffff00,0000ff,ff00ff # Green, yellow, blue, magenta dots
          color_bg: 0d1117 # Dark GitHub background

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            